
USE ROLE sysadmin;
{% if environment == 'PROD' %}
    {% set sufix = '' %}
{% elif environment == 'TEST' %}
    {% set sufix = '_'+ environment %}
{% elif environment == 'DEV' %}
    {% set sufix = '_'+ environment %}
{% endif %} 

CREATE OR REPLACE FUNCTION SOR_AND_STOCK{{ sufix }}.PROCESS.F_COUNTRY_CODE("COUNTRY_CODE" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS '
SELECT TOP 1
    CASE UPPER(COUNTRY_CODE)
        --special cases-----------------------------------------------------------------------------------------------------------
        WHEN = ''ESPAÑA'' THEN ''Spain''
        WHEN = ''ITALIA'' THEN ''Italy''
        WHEN = ''SLOVAK REPUBLIC''     THEN ''Slovakia''
        WHEN = ''UNITED KINGDOM (GB)'' THEN ''United Kingdom''
        WHEN = ''TÜRKIYE''             THEN ''Turkey''
        WHEN = ''UAE''    THEN ''United Arab Emirates''
        WHEN = ''UK''     THEN ''United Kingdom''
        WHEN = ''UNITED ARAB EMIRATE'' THEN ''United Arab Emirates''
        WHEN = ''RSA''    THEN ''South Africa''
        WHEN IS NULL    THEN NULL
        WHEN = ''BEDFORDSHIRE''        THEN ''United Kingdom''
        WHEN = ''BERKSHIRE''           THEN ''United Kingdom''
        WHEN = ''BUCKINGHAMSHIRE''     THEN ''United Kingdom''
        WHEN = ''CAMBRIDGESHIRE''      THEN ''United Kingdom''
        WHEN = ''CHESHIRE''            THEN ''United Kingdom''
        WHEN = ''CORNWALL''            THEN ''United Kingdom''
        WHEN = ''CUMBERLAND''          THEN ''United Kingdom''
        WHEN = ''DERBYSHIRE''          THEN ''United Kingdom''
        WHEN = ''DEVON''  THEN ''United Kingdom''
        WHEN = ''DORSET'' THEN ''United Kingdom''
        WHEN = ''COUNTY DURHAM''       THEN ''United Kingdom''
        WHEN = ''ESSEX''  THEN ''United Kingdom''
        WHEN = ''GLOUCESTERSHIRE''     THEN ''United Kingdom''
        WHEN = ''HAMPSHIRE''           THEN ''United Kingdom''
        WHEN = ''HEREFORDSHIRE''       THEN ''United Kingdom''
        WHEN = ''HERTFORDSHIRE''       THEN ''United Kingdom''
        WHEN = ''HUNTINGDONSHIRE''     THEN ''United Kingdom''
        WHEN = ''KENT''   THEN ''United Kingdom''
        WHEN = ''LANCASHIRE''          THEN ''United Kingdom''
        WHEN = ''LEICESTERSHIRE''      THEN ''United Kingdom''
        WHEN = ''LINCOLNSHIRE''        THEN ''United Kingdom''
        WHEN = ''MIDDLESEX''           THEN ''United Kingdom''
        WHEN = ''NORFOLK''             THEN ''United Kingdom''
        WHEN = ''NORTHAMPTONSHIRE''    THEN ''United Kingdom''
        WHEN = ''NORTHUMBERLAND''      THEN ''United Kingdom''
        WHEN = ''NOTTINGHAMSHIRE''     THEN ''United Kingdom''
        WHEN = ''OXFORDSHIRE''         THEN ''United Kingdom''
        WHEN = ''RUTLAND''             THEN ''United Kingdom''
        WHEN = ''SHROPSHIRE''          THEN ''United Kingdom''
        WHEN = ''SOMERSET''            THEN ''United Kingdom''
        WHEN = ''STAFFORDSHIRE''       THEN ''United Kingdom''
        WHEN = ''SUFFOLK''             THEN ''United Kingdom''
        WHEN = ''SURREY'' THEN ''United Kingdom''
        WHEN = ''SUSSEX'' THEN ''United Kingdom''
        WHEN = ''WARWICKSHIRE''        THEN ''United Kingdom''
        WHEN = ''WESTMORLAND''         THEN ''United Kingdom''
        WHEN = ''WILTSHIRE''           THEN ''United Kingdom''
        WHEN = ''WORCESTERSHIRE''      THEN ''United Kingdom''
        WHEN = ''YORKSHIRE''           THEN ''United Kingdom''
        WHEN = ''SAINT-MARTIN (FR)''   THEN ''France''
        --en full names----------------------------------------------------------------------------------------------------------------
        WHEN ''AFGHANISTAN''         THEN ''Afghanistan''
        WHEN ''ÅLAND ISLANDS''       THEN ''Finland''
        WHEN ''ALBANIA''             THEN ''Albania''
        WHEN ''ALGERIA''             THEN ''Algeria''
        WHEN ''AMERICAN SAMOA''      THEN ''United States''
        WHEN ''ANDORRA''             THEN ''Andorra''
        WHEN ''ANGOLA'' THEN ''Angola''
        WHEN ''ANGUILLA''            THEN ''United Kingdom''
        WHEN ''ANTARCTICA''          THEN ''Antarctica''
        WHEN ''ANTIGUA AND BARBUDA'' THEN ''Antigua and Barbuda''
        WHEN ''ARGENTINA''           THEN ''Argentina''
        WHEN ''ARMENIA''             THEN ''Armenia''
        WHEN ''ARUBA''  THEN ''Netherlands''
        WHEN ''AUSTRALIA''           THEN ''Australia''
        WHEN ''AUSTRIA''             THEN ''Austria''
        WHEN ''AZERBAIJAN''          THEN ''Azerbaijan''
        WHEN ''BAHAMAS''             THEN ''Bahamas''
        WHEN ''BAHRAIN''             THEN ''Bahrain''
        WHEN ''BANGLADESH''          THEN ''Bangladesh''
        WHEN ''BARBADOS''            THEN ''Barbados''
        WHEN ''BELARUS''             THEN ''Belarus''
        WHEN ''BELGIUM''             THEN ''Belgium''
        WHEN ''BELIZE'' THEN ''Belize''
        WHEN ''BENIN''  THEN ''Benin''
        WHEN ''BERMUDA''             THEN ''United Kingdom''
        WHEN ''BHUTAN'' THEN ''Bhutan''
        WHEN ''BOLIVIA, PLURINATIONAL STATE OF'' THEN ''Bolivia, Plurinational State of''
        WHEN ''BONAIRE, SINT EUSTATIUS AND SABA'' THEN ''Netherlands''
        WHEN ''BOSNIA AND HERZEGOVINA'' THEN ''Bosnia and Herzegovina''
        WHEN ''BOTSWANA''            THEN ''Botswana''
        WHEN ''BOUVET ISLAND''       THEN ''Norway''
        WHEN ''BRAZIL'' THEN ''Brazil''
        WHEN ''BRITISH INDIAN OCEAN TERRITORY'' THEN ''United Kingdom''
        WHEN ''BRUNEI DARUSSALAM''   THEN ''Brunei Darussalam''
        WHEN ''BULGARIA''            THEN ''Bulgaria''
        WHEN ''BURKINA FASO''        THEN ''Burkina Faso''
        WHEN ''BURUNDI''             THEN ''Burundi''
        WHEN ''CAMBODIA''            THEN ''Cambodia''
        WHEN ''CAMEROON''            THEN ''Cameroon''
        WHEN ''CANADA'' THEN ''Canada''
        WHEN ''CAPE VERDE''          THEN ''Cape Verde''
        WHEN ''CAYMAN ISLANDS''      THEN ''United Kingdom''
        WHEN ''CENTRAL AFRICAN REPUBLIC'' THEN ''Central African Republic''
        WHEN ''CHAD''   THEN ''Chad''
        WHEN ''CHILE''  THEN ''Chile''
        WHEN ''CHINA''  THEN ''China''
        WHEN ''CHRISTMAS ISLAND''    THEN ''Australia''
        WHEN ''COCOS (KEELING) ISLANDS'' THEN ''Australia''
        WHEN ''COLOMBIA''            THEN ''Colombia''
        WHEN ''COMOROS''             THEN ''Comoros''
        WHEN ''CONGO''  THEN ''Congo''
        WHEN ''CONGO, THE DEMOCRATIC REPUBLIC OF THE'' THEN ''Congo, the Democratic Republic of the''
        WHEN ''COOK ISLANDS''       THEN ''New Zealand''
        WHEN ''COSTA RICA''         THEN ''Costa Rica''
        WHEN ''CÔTE D\\''IVOIRE''      THEN ''Côte d\\''Ivoire''
        WHEN ''CROATIA''            THEN ''Croatia''
        WHEN ''CUBA''  THEN ''Cuba''
        WHEN ''CURAÇAO''            THEN ''Netherlands''
        WHEN ''CYPRUS''             THEN ''Cyprus''
        WHEN ''CZECH REPUBLIC''     THEN ''Czech Republic''
        WHEN ''DENMARK''            THEN ''Denmark''
        WHEN ''DJIBOUTI''           THEN ''Djibouti''
        WHEN ''DOMINICA''           THEN ''Dominica''
        WHEN ''DOMINICAN REPUBLIC'' THEN ''Dominican Republic''
        WHEN ''ECUADOR''            THEN ''Ecuador''
        WHEN ''EGYPT'' THEN ''Egypt''
        WHEN ''EL SALVADOR''        THEN ''El Salvador''
        WHEN ''EQUATORIAL GUINEA''  THEN ''Equatorial Guinea''
        WHEN ''ERITREA'' THEN ''Eritrea''
        WHEN ''ESTONIA'' THEN ''Estonia''
        WHEN ''ETHIOPIA'' THEN ''Ethiopia''
        WHEN ''FALKLAND ISLANDS (MALVINAS)'' THEN ''United Kingdom''
        WHEN ''FAROE ISLANDS'' THEN ''Denmark''
        WHEN ''FIJI'' THEN ''Fiji''
        WHEN ''FINLAND'' THEN ''Finland''
        WHEN ''FRANCE'' THEN ''France''
        WHEN ''FRENCH GUIANA'' THEN ''France''
        WHEN ''FRENCH POLYNESIA'' THEN ''France''
        WHEN ''FRENCH SOUTHERN TERRITORIES'' THEN ''France''
        WHEN ''GABON'' THEN ''Gabon''
        WHEN ''GAMBIA'' THEN ''Gambia''
        WHEN ''GEORGIA'' THEN ''Georgia''
        WHEN ''GERMANY'' THEN ''Germany''
        WHEN ''GHANA'' THEN ''Ghana''
        WHEN ''GIBRALTAR'' THEN ''United Kingdom''
        WHEN ''GREECE'' THEN ''Greece''
        WHEN ''GREENLAND'' THEN ''Denmark''
        WHEN ''GRENADA'' THEN ''Grenada''
        WHEN ''GUADELOUPE'' THEN ''France''
        WHEN ''GUAM'' THEN ''United States''
        WHEN ''GUATEMALA'' THEN ''Guatemala''
        WHEN ''GUERNSEY'' THEN ''United Kingdom''
        WHEN ''GUINEA'' THEN ''Guinea''
        WHEN ''GUINEA-BISSAU'' THEN ''Guinea-Bissau''
        WHEN ''GUYANA'' THEN ''Guyana''
        WHEN ''HAITI'' THEN ''Haiti''
        WHEN ''HEARD ISLAND AND MCDONALD ISLANDS'' THEN ''Australia''
        WHEN ''HOLY SEE (VATICAN CITY STATE)'' THEN ''Holy See (Vatican City State)''
        WHEN ''HONDURAS'' THEN ''Honduras''
        WHEN ''HONG KONG'' THEN ''China''
        WHEN ''HUNGARY'' THEN ''Hungary''
        WHEN ''ICELAND'' THEN ''Iceland''
        WHEN ''INDIA'' THEN ''India''
        WHEN ''INDONESIA'' THEN ''Indonesia''
        WHEN ''IRAN, ISLAMIC REPUBLIC OF'' THEN ''Iran, Islamic Republic of''
        WHEN ''IRAQ'' THEN ''Iraq''
        WHEN ''IRELAND'' THEN ''Ireland''
        WHEN ''ISLE OF MAN'' THEN ''United Kingdom''
        WHEN ''ISRAEL'' THEN ''Israel''
        WHEN ''ITALY'' THEN ''Italy''
        WHEN ''JAMAICA'' THEN ''Jamaica''
        WHEN ''JAPAN'' THEN ''Japan''
        WHEN ''JERSEY'' THEN ''United Kingdom''
        WHEN ''JORDAN'' THEN ''Jordan''
        WHEN ''KAZAKHSTAN'' THEN ''Kazakhstan''
        WHEN ''KENYA'' THEN ''Kenya''
        WHEN ''KIRIBATI'' THEN ''Kiribati''
        WHEN ''KOREA, DEMOCRATIC PEOPLE\\''S REPUBLIC OF'' THEN ''Korea, Democratic People\\''s Republic of''
        WHEN ''KOREA, REPUBLIC OF'' THEN ''Korea, Republic of''
        WHEN ''KUWAIT'' THEN ''Kuwait''
        WHEN ''KYRGYZSTAN'' THEN ''Kyrgyzstan''
        WHEN ''LAO PEOPLE\\''S DEMOCRATIC REPUBLIC'' THEN ''Lao People\\''s Democratic Republic''
        WHEN ''LATVIA'' THEN ''Latvia''
        WHEN ''LEBANON'' THEN ''Lebanon''
        WHEN ''LESOTHO'' THEN ''Lesotho''
        WHEN ''LIBERIA'' THEN ''Liberia''
        WHEN ''LIBYA'' THEN ''Libya''
        WHEN ''LIECHTENSTEIN'' THEN ''Liechtenstein''
        WHEN ''LITHUANIA'' THEN ''Lithuania''
        WHEN ''LUXEMBOURG'' THEN ''Luxembourg''
        WHEN ''MACAO'' THEN ''China''
        WHEN ''MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF'' THEN ''Macedonia, the Former Yugoslav Republic of''
        WHEN ''MADAGASCAR'' THEN ''Madagascar''
        WHEN ''MALAWI'' THEN ''Malawi''
        WHEN ''MALAYSIA'' THEN ''Malaysia''
        WHEN ''MALDIVES'' THEN ''Maldives''
        WHEN ''MALI'' THEN ''Mali''
        WHEN ''MALTA'' THEN ''Malta''
        WHEN ''MARSHALL ISLANDS'' THEN ''Marshall Islands''
        WHEN ''MARTINIQUE'' THEN ''France''
        WHEN ''MAURITANIA'' THEN ''Mauritania''
        WHEN ''MAURITIUS'' THEN ''Mauritius''
        WHEN ''MAYOTTE'' THEN ''France''
        WHEN ''MEXICO'' THEN ''Mexico''
        WHEN ''MICRONESIA, FEDERATED STATES OF'' THEN ''Micronesia, Federated States of''
        WHEN ''MOLDOVA, REPUBLIC OF'' THEN ''Moldova, Republic of''
        WHEN ''MONACO'' THEN ''Monaco''
        WHEN ''MONGOLIA'' THEN ''Mongolia''
        WHEN ''MONTENEGRO'' THEN ''Montenegro''
        WHEN ''MONTSERRAT'' THEN ''United Kingdom''
        WHEN ''MOROCCO'' THEN ''Morocco''
        WHEN ''MOZAMBIQUE'' THEN ''Mozambique''
        WHEN ''MYANMAR'' THEN ''Myanmar''
        WHEN ''NAMIBIA'' THEN ''Namibia''
        WHEN ''NAURU'' THEN ''Nauru''
        WHEN ''NEPAL'' THEN ''Nepal''
        WHEN ''NETHERLANDS'' THEN ''Netherlands''
        WHEN ''NEW CALEDONIA'' THEN ''France''
        WHEN ''NEW ZEALAND'' THEN ''New Zealand''
        WHEN ''NICARAGUA'' THEN ''Nicaragua''
        WHEN ''NIGER'' THEN ''Niger''
        WHEN ''NIGERIA'' THEN ''Nigeria''
        WHEN ''NIUE'' THEN ''Niue''
        WHEN ''NORFOLK ISLAND'' THEN ''Australia''
        WHEN ''NORTHERN MARIANA ISLANDS'' THEN ''United States''
        WHEN ''NORWAY'' THEN ''Norway''
        WHEN ''OMAN'' THEN ''Oman''
        WHEN ''PAKISTAN'' THEN ''Pakistan''
        WHEN ''PALAU'' THEN ''Palau''
        WHEN ''PALESTINE, STATE OF'' THEN ''Palestine, State of''
        WHEN ''PANAMA'' THEN ''Panama''
        WHEN ''PAPUA NEW GUINEA'' THEN ''Papua New Guinea''
        WHEN ''PARAGUAY'' THEN ''Paraguay''
        WHEN ''PERU'' THEN ''Peru''
        WHEN ''PHILIPPINES'' THEN ''Philippines''
        WHEN ''PITCAIRN'' THEN ''United Kingdom''
        WHEN ''POLAND'' THEN ''Poland''
        WHEN ''PORTUGAL'' THEN ''Portugal''
        WHEN ''PUERTO RICO'' THEN ''United States''
        WHEN ''QATAR'' THEN ''Qatar''
        WHEN ''RÉUNION'' THEN ''France''
        WHEN ''ROMANIA'' THEN ''Romania''
        WHEN ''RUSSIAN FEDERATION'' THEN ''Russian Federation''
        WHEN ''RWANDA'' THEN ''Rwanda''
        WHEN ''SAINT BARTHÉLEMY'' THEN ''France''
        WHEN ''SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA'' THEN ''United Kingdom''
        WHEN ''SAINT KITTS AND NEVIS'' THEN ''Saint Kitts and Nevis''
        WHEN ''SAINT LUCIA'' THEN ''Saint Lucia''
        WHEN ''SAINT MARTIN (FRENCH PART)'' THEN ''France''
        WHEN ''SAINT PIERRE AND MIQUELON'' THEN ''Saint Pierre and Miquelon''
        WHEN ''SAINT VINCENT AND THE GRENADINES'' THEN ''Saint Vincent and the Grenadines''
        WHEN ''SAMOA'' THEN ''Samoa''
        WHEN ''SAN MARINO'' THEN ''San Marino''
        WHEN ''SAO TOME AND PRINCIPE'' THEN ''Sao Tome and Principe''
        WHEN ''SAUDI ARABIA'' THEN ''Saudi Arabia''
        WHEN ''SENEGAL'' THEN ''Senegal''
        WHEN ''SERBIA'' THEN ''Serbia''
        WHEN ''SEYCHELLES'' THEN ''Seychelles''
        WHEN ''SIERRA LEONE'' THEN ''Sierra Leone''
        WHEN ''SINGAPORE'' THEN ''Singapore''
        WHEN ''SINT MAARTEN (DUTCH PART)'' THEN ''Netherlands''
        WHEN ''SLOVAKIA'' THEN ''Slovakia''
        WHEN ''SLOVENIA'' THEN ''Slovenia''
        WHEN ''SOLOMON ISLANDS'' THEN ''Solomon Islands''
        WHEN ''SOMALIA'' THEN ''Somalia''
        WHEN ''SOUTH AFRICA'' THEN ''South Africa''
        WHEN ''SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'' THEN ''United Kingdom''
        WHEN ''SOUTH SUDAN'' THEN ''South Sudan''
        WHEN ''SPAIN'' THEN ''Spain''
        WHEN ''SRI LANKA'' THEN ''Sri Lanka''
        WHEN ''SUDAN'' THEN ''Sudan''
        WHEN ''SURINAME'' THEN ''Suriname''
        WHEN ''SVALBARD AND JAN MAYEN'' THEN ''Norway''
        WHEN ''ESWATINI'' THEN ''Eswatini''
        WHEN ''SWEDEN'' THEN ''Sweden''
        WHEN ''SWITZERLAND'' THEN ''Switzerland''
        WHEN ''SYRIAN ARAB REPUBLIC'' THEN ''Syrian Arab Republic''
        WHEN ''TAIWAN, PROVINCE OF CHINA'' THEN ''Taiwan, Province of China''
        WHEN ''TAJIKISTAN'' THEN ''Tajikistan''
        WHEN ''TANZANIA, UNITED REPUBLIC OF'' THEN ''Tanzania, United Republic of''
        WHEN ''THAILAND'' THEN ''Thailand''
        WHEN ''TIMOR-LESTE'' THEN ''Timor-Leste''
        WHEN ''TOGO'' THEN ''Togo''
        WHEN ''TOKELAU'' THEN ''New Zealand''
        WHEN ''TONGA'' THEN ''Tonga''
        WHEN ''TRINIDAD AND TOBAGO'' THEN ''Trinidad and Tobago''
        WHEN ''TUNISIA'' THEN ''Tunisia''
        WHEN ''TURKEY'' THEN ''Turkey''
        WHEN ''TURKMENISTAN'' THEN ''Turkmenistan''
        WHEN ''TURKS AND CAICOS ISLANDS'' THEN ''United Kingdom''
        WHEN ''TUVALU'' THEN ''Tuvalu''
        WHEN ''UGANDA'' THEN ''Uganda''
        WHEN ''UKRAINE'' THEN ''Ukraine''
        WHEN ''UNITED ARAB EMIRATES'' THEN ''United Arab Emirates''
        WHEN ''UNITED KINGDOM'' THEN ''United Kingdom''
        WHEN ''UNITED STATES'' THEN ''United States''
        WHEN ''UNITED STATES MINOR OUTLYING ISLANDS'' THEN ''United States''
        WHEN ''URUGUAY'' THEN ''Uruguay''
        WHEN ''UZBEKISTAN'' THEN ''Uzbekistan''
        WHEN ''VANUATU'' THEN ''Vanuatu''
        WHEN ''VENEZUELA, BOLIVARIAN REPUBLIC OF'' THEN ''Venezuela, Bolivarian Republic of''
        WHEN ''VIET NAM'' THEN ''Viet Nam''
        WHEN ''VIRGIN ISLANDS, BRITISH'' THEN ''United Kingdom''
        WHEN ''VIRGIN ISLANDS, U.S.'' THEN ''United States''
        WHEN ''WALLIS AND FUTUNA'' THEN ''France''
        WHEN ''WESTERN SAHARA'' THEN ''Western Sahara''
        WHEN ''YEMEN'' THEN ''Yemen''
        WHEN ''ZAMBIA'' THEN ''Zambia''
        WHEN ''ZIMBABWE'' THEN ''Zimbabwe''
        --de full names----------------------------------------------------------------------------------------------------------------
        WHEN ''AFGHANISTAN'' THEN ''Afghanistan''
        WHEN ''ÅLAND-INSELN'' THEN ''Finland''
        WHEN ''ALBANIEN'' THEN ''Albania''
        WHEN ''ALGERIEN'' THEN ''Algeria''
        WHEN ''AMERIKANISCH-SAMOA'' THEN ''United States''
        WHEN ''ANDORRA'' THEN ''Andorra''
        WHEN ''ANGOLA'' THEN ''Angola''
        WHEN ''ANGUILLA'' THEN ''United Kingdom''
        WHEN ''ANTARKTIS'' THEN ''Antarctica''
        WHEN ''ANTIGUA UND BARBUDA'' THEN ''Antigua and Barbuda''
        WHEN ''ARGENTINIEN'' THEN ''Argentina''
        WHEN ''ARMENIEN'' THEN ''Armenia''
        WHEN ''ARUBA'' THEN ''Netherlands''
        WHEN ''AUSTRALIEN'' THEN ''Australia''
        WHEN ''ÖSTERREICH'' THEN ''Austria''
        WHEN ''ASERBAIDSCHAN'' THEN ''Azerbaijan''
        WHEN ''BAHAMAS'' THEN ''Bahamas''
        WHEN ''BAHRAIN'' THEN ''Bahrain''
        WHEN ''BANGLADESCH'' THEN ''Bangladesh''
        WHEN ''BARBADOS'' THEN ''Barbados''
        WHEN ''WEIßRUSSLAND'' THEN ''Belarus''
        WHEN ''BELGIEN'' THEN ''Belgium''
        WHEN ''BELIZE'' THEN ''Belize''
        WHEN ''BENIN'' THEN ''Benin''
        WHEN ''BERMUDA'' THEN ''United Kingdom''
        WHEN ''BHUTAN'' THEN ''Bhutan''
        WHEN ''BOLIVIEN, PLURINATIONALER STAAT'' THEN ''Bolivia, Plurinational State of''
        WHEN ''BONAIRE, SINT EUSTATIUS UND SABA'' THEN ''Netherlands''
        WHEN ''BOSNIEN UND HERZEGOWINA'' THEN ''Bosnia and Herzegovina''
        WHEN ''BOTSWANA'' THEN ''Botswana''
        WHEN ''BOUVETINSEL'' THEN ''Norway''
        WHEN ''BRASILIEN'' THEN ''Brazil''
        WHEN ''BRITISCHES TERRITORIUM IM INDISCHEN OZEAN'' THEN ''United Kingdom''
        WHEN ''BRUNEI DARUSSALAM'' THEN ''Brunei Darussalam''
        WHEN ''BULGARIEN'' THEN ''Bulgaria''
        WHEN ''BURKINA FASO'' THEN ''Burkina Faso''
        WHEN ''BURUNDI'' THEN ''Burundi''
        WHEN ''KAMBODSCHA'' THEN ''Cambodia''
        WHEN ''KAMERUN'' THEN ''Cameroon''
        WHEN ''KANADA'' THEN ''Canada''
        WHEN ''KAP VERDE'' THEN ''Cape Verde''
        WHEN ''KAIMANINSELN'' THEN ''United Kingdom''
        WHEN ''ZENTRALAFRIKANISCHE REPUBLIK'' THEN ''Central African Republic''
        WHEN ''TSCHAD'' THEN ''Chad''
        WHEN ''CHILE'' THEN ''Chile''
        WHEN ''CHINA'' THEN ''China''
        WHEN ''WEIHNACHTSINSEL'' THEN ''Australia''
        WHEN ''KOKOS (KEELING) INSELN'' THEN ''Australia''
        WHEN ''KOLUMBIEN'' THEN ''Colombia''
        WHEN ''KOMOREN'' THEN ''Comoros''
        WHEN ''KONGO'' THEN ''Congo''
        WHEN ''DEMOKRATISCHE REPUBLIK KONGO'' THEN ''Congo, the Democratic Republic of the''
        WHEN ''COOKINSELN'' THEN ''New Zealand''
        WHEN ''COSTA RICA'' THEN ''Costa Rica''
        WHEN ''ELFENBEINKÜSTE'' THEN ''Côte d\\''Ivoire''
        WHEN ''KROATIEN'' THEN ''Croatia''
        WHEN ''KUBA'' THEN ''Cuba''
        WHEN ''CURAÇAO'' THEN ''Netherlands''
        WHEN ''ZYPERN'' THEN ''Cyprus''
        WHEN ''TSCHECHISCHE REPUBLIK'' THEN ''Czech Republic''
        WHEN ''DÄNEMARK'' THEN ''Denmark''
        WHEN ''DSCHIBUTI'' THEN ''Djibouti''
        WHEN ''DOMINICA'' THEN ''Dominica''
        WHEN ''DOMINIKANISCHE REPUBLIK'' THEN ''Dominican Republic''
        WHEN ''ECUADOR'' THEN ''Ecuador''
        WHEN ''ÄGYPTEN'' THEN ''Egypt''
        WHEN ''EL SALVADOR'' THEN ''El Salvador''
        WHEN ''ÄQUATORIALGUINEA'' THEN ''Equatorial Guinea''
        WHEN ''ERITREA'' THEN ''Eritrea''
        WHEN ''ESTLAND'' THEN ''Estonia''
        WHEN ''ÄTHIOPIEN'' THEN ''Ethiopia''
        WHEN ''FALKLANDINSELN (MALWINEN)'' THEN ''United Kingdom''
        WHEN ''FÄRÖER'' THEN ''Denmark''
        WHEN ''FIDSCHI'' THEN ''Fiji''
        WHEN ''FINNLAND'' THEN ''Finland''
        WHEN ''FRANKREICH'' THEN ''France''
        WHEN ''FRANZÖSISCH-GUAYANA'' THEN ''France''
        WHEN ''FRANZÖSISCH-POLYNESIEN'' THEN ''France''
        WHEN ''FRANZÖSISCHE SÜDGEBIETE'' THEN ''France''
        WHEN ''GABUN'' THEN ''Gabon''
        WHEN ''GAMBIA'' THEN ''Gambia''
        WHEN ''GEORGIEN'' THEN ''Georgia''
        WHEN ''DEUTSCHLAND'' THEN ''Germany''
        WHEN ''GHANA'' THEN ''Ghana''
        WHEN ''GIBRALTAR'' THEN ''United Kingdom''
        WHEN ''GRIECHENLAND'' THEN ''Greece''
        WHEN ''GRÖNLAND'' THEN ''Denmark''
        WHEN ''GRENADA'' THEN ''Grenada''
        WHEN ''GUADELOUPE'' THEN ''France''
        WHEN ''GUAM'' THEN ''United States''
        WHEN ''GUATEMALA'' THEN ''Guatemala''
        WHEN ''GUERNSEY'' THEN ''United Kingdom''
        WHEN ''GUINEA'' THEN ''Guinea''
        WHEN ''GUINEA-BISSAU'' THEN ''Guinea-Bissau''
        WHEN ''GUYANA'' THEN ''Guyana''
        WHEN ''HAITI'' THEN ''Haiti''
        WHEN ''HEARD UND MCDONALDINSELN'' THEN ''Australia''
        WHEN ''HEILIGER STUHL (VATIKANSTADT)'' THEN ''Holy See (Vatican City State)''
        WHEN ''HONDURAS'' THEN ''Honduras''
        WHEN ''HONG KONG'' THEN ''China''
        WHEN ''UNGARN'' THEN ''Hungary''
        WHEN ''ISLAND'' THEN ''Iceland''
        WHEN ''INDIEN'' THEN ''India''
        WHEN ''INDONESIEN'' THEN ''Indonesia''
        WHEN ''IRAN, ISLAMISCHE REPUBLIK'' THEN ''Iran, Islamic Republic of''
        WHEN ''IRAK'' THEN ''Iraq''
        WHEN ''IRLAND'' THEN ''Ireland''
        WHEN ''ISLE OF MAN'' THEN ''United Kingdom''
        WHEN ''ISRAEL'' THEN ''Israel''
        WHEN ''ITALIEN'' THEN ''Italy''
        WHEN ''JAMAIKA'' THEN ''Jamaica''
        WHEN ''JAPAN'' THEN ''Japan''
        WHEN ''JERSEY'' THEN ''United Kingdom''
        WHEN ''JORDANIEN'' THEN ''Jordan''
        WHEN ''KASACHSTAN'' THEN ''Kazakhstan''
        WHEN ''KENIA'' THEN ''Kenya''
        WHEN ''KIRIBATI'' THEN ''Kiribati''
        WHEN ''KOREA, DEMOKRATISCHE VOLKSREPUBLIK'' THEN ''Korea, Democratic People\\''s Republic of''
        WHEN ''KOREA, REPUBLIK'' THEN ''Korea, Republic of''
        WHEN ''KUWAIT'' THEN ''Kuwait''
        WHEN ''KIRGISISTAN'' THEN ''Kyrgyzstan''
        WHEN ''LAOTISCHE DEMOKRATISCHE VOLKSREPUBLIK'' THEN ''Lao People\\''s Democratic Republic''
        WHEN ''LETTLAND'' THEN ''Latvia''
        WHEN ''LIBANON'' THEN ''Lebanon''
        WHEN ''LESOTHO'' THEN ''Lesotho''
        WHEN ''LIBERIA'' THEN ''Liberia''
        WHEN ''LIBYEN'' THEN ''Libya''
        WHEN ''LIECHTENSTEIN'' THEN ''Liechtenstein''
        WHEN ''LITAUEN'' THEN ''Lithuania''
        WHEN ''LUXEMBURG'' THEN ''Luxembourg''
        WHEN ''MACAU'' THEN ''China''
        WHEN ''MAZEDONIEN, EHEMALIGE JUGOSLAWISCHE REPUBLIK'' THEN ''Macedonia, the Former Yugoslav Republic of''
        WHEN ''MADAGASKAR'' THEN ''Madagascar''
        WHEN ''MALAWI'' THEN ''Malawi''
        WHEN ''MALAYSIA'' THEN ''Malaysia''
        WHEN ''MALEDIVEN'' THEN ''Maldives''
        WHEN ''SIE HATTEN'' THEN ''Mali''
        WHEN ''MALTA'' THEN ''Malta''
        WHEN ''MARSHALLINSELN'' THEN ''Marshall Islands''
        WHEN ''MARTINIQUE'' THEN ''France''
        WHEN ''MAURETANIEN'' THEN ''Mauritania''
        WHEN ''MAURITIUS'' THEN ''Mauritius''
        WHEN ''MAYOTTE'' THEN ''France''
        WHEN ''MEXIKO'' THEN ''Mexico''
        WHEN ''MIKRONESIEN, FÖDERIERTE STAATEN VON'' THEN ''Micronesia, Federated States of''
        WHEN ''REPUBLIK MOLDAU VON'' THEN ''Moldova, Republic of''
        WHEN ''MONACO'' THEN ''Monaco''
        WHEN ''MONGOLEI'' THEN ''Mongolia''
        WHEN ''MONTENEGRO'' THEN ''Montenegro''
        WHEN ''MONTSERRAT'' THEN ''United Kingdom''
        WHEN ''MAROKKO'' THEN ''Morocco''
        WHEN ''MOSAMBIK'' THEN ''Mozambique''
        WHEN ''MYANMAR'' THEN ''Myanmar''
        WHEN ''NAMIBIA'' THEN ''Namibia''
        WHEN ''NAURU'' THEN ''Nauru''
        WHEN ''NEPAL'' THEN ''Nepal''
        WHEN ''NIEDERLANDE'' THEN ''Netherlands''
        WHEN ''NEUKALEDONIEN'' THEN ''France''
        WHEN ''NEUSEELAND'' THEN ''New Zealand''
        WHEN ''NICARAGUA'' THEN ''Nicaragua''
        WHEN ''NIGER'' THEN ''Niger''
        WHEN ''NIGERIA'' THEN ''Nigeria''
        WHEN ''NIUE'' THEN ''Niue''
        WHEN ''NORFOLKINSEL'' THEN ''Australia''
        WHEN ''NÖRDLICHE MARIANEN'' THEN ''United States''
        WHEN ''NORWEGEN'' THEN ''Norway''
        WHEN ''OMAN'' THEN ''Oman''
        WHEN ''PAKISTAN'' THEN ''Pakistan''
        WHEN ''PALAU'' THEN ''Palau''
        WHEN ''STAAT PALÄSTINA'' THEN ''Palestine, State of''
        WHEN ''PANAMA'' THEN ''Panama''
        WHEN ''PAPUA-NEUGUINEA'' THEN ''Papua New Guinea''
        WHEN ''PARAGUAY'' THEN ''Paraguay''
        WHEN ''PERU'' THEN ''Peru''
        WHEN ''PHILIPPINEN'' THEN ''Philippines''
        WHEN ''PITCAIRNINSELN'' THEN ''United Kingdom''
        WHEN ''POLEN'' THEN ''Poland''
        WHEN ''PORTUGAL'' THEN ''Portugal''
        WHEN ''PUERTO RICO'' THEN ''United States''
        WHEN ''KATAR'' THEN ''Qatar''
        WHEN ''RÉUNION'' THEN ''France''
        WHEN ''RUMÄNIEN'' THEN ''Romania''
        WHEN ''RUSSISCHE FÖDERATION'' THEN ''Russian Federation''
        WHEN ''RUANDA'' THEN ''Rwanda''
        WHEN ''ST. BARTHÉLEMY'' THEN ''France''
        WHEN ''ST. HELENA, ASCENSION UND TRISTAN DA CUNHA'' THEN ''United Kingdom''
        WHEN ''ST. KITTS UND NEVIS'' THEN ''Saint Kitts and Nevis''
        WHEN ''ST. LUCIA'' THEN ''Saint Lucia''
        WHEN ''ST. MARTIN (FRANZÖSISCHER TEIL)'' THEN ''France''
        WHEN ''ST. PIERRE UND MIQUELON'' THEN ''Saint Pierre and Miquelon''
        WHEN ''ST. VINCENT UND DIE GRENADINEN'' THEN ''Saint Vincent and the Grenadines''
        WHEN ''SAMOA'' THEN ''Samoa''
        WHEN ''SAN MARINO'' THEN ''San Marino''
        WHEN ''SÃO TOMÉ UND PRÍNCIPE PRINCIPE'' THEN ''Sao Tome and Principe''
        WHEN ''SAUDI-ARABIEN'' THEN ''Saudi Arabia''
        WHEN ''SENEGAL'' THEN ''Senegal''
        WHEN ''SERBIEN'' THEN ''Serbia''
        WHEN ''SEYCHELLEN'' THEN ''Seychelles''
        WHEN ''SIERRA LEONE'' THEN ''Sierra Leone''
        WHEN ''SINGAPUR'' THEN ''Singapore''
        WHEN ''SINT MAARTEN (NIEDERLÄNDISCHER TEIL)'' THEN ''Netherlands''
        WHEN ''SLOWAKEI'' THEN ''Slovakia''
        WHEN ''SLOWENIEN'' THEN ''Slovenia''
        WHEN ''SALOMONEN'' THEN ''Solomon Islands''
        WHEN ''SOMALIA'' THEN ''Somalia''
        WHEN ''SÜDAFRIKA'' THEN ''South Africa''
        WHEN ''SÜDGEORGIEN UND DIE SÜDLICHEN SANDWICHINSELN'' THEN ''United Kingdom''
        WHEN ''SÜDSUDAN'' THEN ''South Sudan''
        WHEN ''SPANIEN'' THEN ''Spain''
        WHEN ''SRI LANKA'' THEN ''Sri Lanka''
        WHEN ''SUDAN'' THEN ''Sudan''
        WHEN ''SURINAME'' THEN ''Suriname''
        WHEN ''SVALBARD UND JAN MAYEN'' THEN ''Norway''
        WHEN ''ESWATINI'' THEN ''Eswatini''
        WHEN ''SCHWEDEN'' THEN ''Sweden''
        WHEN ''SCHWEIZ'' THEN ''Switzerland''
        WHEN ''SYRIEN'' THEN ''Syrian Arab Republic''
        WHEN ''TAIWAN (PROVINZ CHINA)'' THEN ''Taiwan, Province of China''
        WHEN ''TADSCHIKISTAN'' THEN ''Tajikistan''
        WHEN ''TANSANIA (VEREINIGTE REPUBLIK)'' THEN ''Tanzania, United Republic of''
        WHEN ''THAILAND'' THEN ''Thailand''
        WHEN ''TIMOR-LESTE'' THEN ''Timor-Leste''
        WHEN ''TOGO'' THEN ''Togo''
        WHEN ''TOKELAU'' THEN ''New Zealand''
        WHEN ''TONGA'' THEN ''Tonga''
        WHEN ''TRINIDAD UND TOBAGO'' THEN ''Trinidad and Tobago''
        WHEN ''TUNESIEN'' THEN ''Tunisia''
        WHEN ''TÜRKEI'' THEN ''Turkey''
        WHEN ''TURKMENISTAN'' THEN ''Turkmenistan''
        WHEN ''TURKS- UND CAICOSINSELN'' THEN ''United Kingdom''
        WHEN ''TUVALU'' THEN ''Tuvalu''
        WHEN ''UGANDA'' THEN ''Uganda''
        WHEN ''UKRAINE'' THEN ''Ukraine''
        WHEN ''VEREINIGTE ARABISCHE EMIRATE'' THEN ''United Arab Emirates''
        WHEN ''VEREINIGTES KÖNIGREICH'' THEN ''United Kingdom''
        WHEN ''VEREINIGTE STAATEN'' THEN ''United States''
        WHEN ''VEREINIGTE STAATEN (KLEINERE ABGELEGENE GEBIETE) INSELN'' THEN ''United States''
        WHEN ''URUGUAY'' THEN ''Uruguay''
        WHEN ''USBEKISTAN'' THEN ''Uzbekistan''
        WHEN ''VANUATU'' THEN ''Vanuatu''
        WHEN ''VENEZUELA, BOLIVARISCHE REPUBLIK'' THEN ''Venezuela, Bolivarian Republic of''
        WHEN ''VIETNAM'' THEN ''Viet Nam''
        WHEN ''BRITISCHE JUNGFERNINSELN'' THEN ''United Kingdom''
        WHEN ''JUNGFERNINSELN, USA'' THEN ''United States''
        WHEN ''WALLIS UND FUTUNA'' THEN ''France''
        WHEN ''WESTSAHARA'' THEN ''Western Sahara''
        WHEN ''JEMEN'' THEN ''Yemen''
        WHEN ''SAMBIA'' THEN ''Zambia''
        WHEN ''SIMBABWE'' THEN ''Zimbabwe''
        --fr full names----------------------------------------------------------------------------------------------------------------
        WHEN ''AFGHANISTAN'' THEN ''Afghanistan''
        WHEN ''ÎLES ÅLAND'' THEN ''Finland''
        WHEN ''ALBANIE'' THEN ''Albania''
        WHEN ''ALGÉRIE'' THEN ''Algeria''
        WHEN ''SAMOA AMÉRICAINES'' THEN ''United States''
        WHEN ''ANDORRE'' THEN ''Andorra''
        WHEN ''ANGOLA'' THEN ''Angola''
        WHEN ''ANGUILLA'' THEN ''United Kingdom''
        WHEN ''ANTARCTIQUE'' THEN ''Antarctica''
        WHEN ''ANTIGUA-ET-BARBUDA'' THEN ''Antigua and Barbuda''
        WHEN ''ARGENTINE'' THEN ''Argentina''
        WHEN ''ARMÉNIE'' THEN ''Armenia''
        WHEN ''ARUBA'' THEN ''Netherlands''
        WHEN ''AUSTRALIE'' THEN ''Australia''
        WHEN ''AUTRICHE'' THEN ''Austria''
        WHEN ''AZERBAÏDJAN'' THEN ''Azerbaijan''
        WHEN ''BAHAMAS'' THEN ''Bahamas''
        WHEN ''BAHREÏN'' THEN ''Bahrain''
        WHEN ''BANGLADESH'' THEN ''Bangladesh''
        WHEN ''BARBADE'' THEN ''Barbados''
        WHEN ''BIÉLORUSSIE'' THEN ''Belarus''
        WHEN ''BELGIQUE'' THEN ''Belgium''
        WHEN ''BÉLIZE'' THEN ''Belize''
        WHEN ''BÉNIN'' THEN ''Benin''
        WHEN ''BERMUDES'' THEN ''United Kingdom''
        WHEN ''BHOUTAN'' THEN ''Bhutan''
        WHEN ''BOLIVIE, ÉTAT PLURINATIONAL DE'' THEN ''Bolivia, Plurinational State of''
        WHEN ''BONAIRE, SAINT-EUSTACHE ET SABA'' THEN ''Netherlands''
        WHEN ''BOSNIE-HERZÉGOVINE'' THEN ''Bosnia and Herzegovina''
        WHEN ''BOTSWANA'' THEN ''Botswana''
        WHEN ''ÎLE BOUVET'' THEN ''Norway''
        WHEN ''BRÉSIL'' THEN ''Brazil''
        WHEN ''TERRITOIRE BRITANNIQUE DE L\\''OCÉAN INDIEN'' THEN ''United Kingdom''
        WHEN ''BRUNÉI DARUSSALAM'' THEN ''Brunei Darussalam''
        WHEN ''BULGARIE'' THEN ''Bulgaria''
        WHEN ''BURKINA FASO'' THEN ''Burkina Faso''
        WHEN ''BURUNDI'' THEN ''Burundi''
        WHEN ''CAMBODGE'' THEN ''Cambodia''
        WHEN ''CAMEROUN'' THEN ''Cameroon''
        WHEN ''CANADA'' THEN ''Canada''
        WHEN ''CAP-VERT'' THEN ''Cape Verde''
        WHEN ''ÎLES CAÏMANS'' THEN ''United Kingdom''
        WHEN ''RÉPUBLIQUE CENTRAFRICAINE'' THEN ''Central African Republic''
        WHEN ''TCHAD'' THEN ''Chad''
        WHEN ''CHILI'' THEN ''Chile''
        WHEN ''CHINE'' THEN ''China''
        WHEN ''ÎLE CHRISTMAS'' THEN ''Australia''
        WHEN ''ÎLES COCOS (KEELING)'' THEN ''Australia''
        WHEN ''COLOMBIE'' THEN ''Colombia''
        WHEN ''COMORES'' THEN ''Comoros''
        WHEN ''CONGO'' THEN ''Congo''
        WHEN ''CONGO, RÉPUBLIQUE DÉMOCRATIQUE DU ÎLES COOK'' THEN ''Congo, the Democratic Republic of the''
        WHEN ''COSTA RICA'' THEN ''Costa Rica''
        WHEN ''CÔTE D\\''IVOIRE'' THEN ''Côte d\\''Ivoire''
        WHEN ''CROATIE'' THEN ''Croatia''
        WHEN ''CUBA'' THEN ''Cuba''
        WHEN ''CURAÇAO'' THEN ''Netherlands''
        WHEN ''CHYPRE'' THEN ''Cyprus''
        WHEN ''RÉPUBLIQUE TCHÈQUE'' THEN ''Czech Republic''
        WHEN ''DANEMARK'' THEN ''Denmark''
        WHEN ''DJIBOUTI'' THEN ''Djibouti''
        WHEN ''DOMINIQUE'' THEN ''Dominica''
        WHEN ''RÉPUBLIQUE DOMINICAINE'' THEN ''Dominican Republic''
        WHEN ''ÉQUATEUR'' THEN ''Ecuador''
        WHEN ''ÉGYPTE'' THEN ''Egypt''
        WHEN ''SALVADOR'' THEN ''El Salvador''
        WHEN ''GUINÉE ÉQUATORIALE'' THEN ''Equatorial Guinea''
        WHEN ''ÉRYTHRÉE'' THEN ''Eritrea''
        WHEN ''ESTONIE'' THEN ''Estonia''
        WHEN ''ÉTHIOPIE'' THEN ''Ethiopia''
        WHEN ''ÎLES MALOUINES (MALVINAS)'' THEN ''United Kingdom''
        WHEN ''ÎLES FÉROÉ'' THEN ''Denmark''
        WHEN ''FIDJI'' THEN ''Fiji''
        WHEN ''FINLANDE'' THEN ''Finland''
        WHEN ''FRANCE'' THEN ''France''
        WHEN ''GUYANE FRANÇAISE'' THEN ''France''
        WHEN ''POLYNÉSIE FRANÇAISE'' THEN ''France''
        WHEN ''TERRES AUSTRALES FRANÇAISES'' THEN ''France''
        WHEN ''GABON'' THEN ''Gabon''
        WHEN ''GAMBIE'' THEN ''Gambia''
        WHEN ''GÉORGIE'' THEN ''Georgia''
        WHEN ''ALLEMAGNE'' THEN ''Germany''
        WHEN ''GHANA'' THEN ''Ghana''
        WHEN ''GIBRALTAR'' THEN ''United Kingdom''
        WHEN ''GRÈCE'' THEN ''Greece''
        WHEN ''GROENLAND'' THEN ''Denmark''
        WHEN ''GRENADE'' THEN ''Grenada''
        WHEN ''GUADELOUPE'' THEN ''France''
        WHEN ''GUAM'' THEN ''United States''
        WHEN ''GUATEMALA'' THEN ''Guatemala''
        WHEN ''GUERNESEY'' THEN ''United Kingdom''
        WHEN ''GUINÉE'' THEN ''Guinea''
        WHEN ''GUINÉE-BISSAU'' THEN ''Guinea-Bissau''
        WHEN ''GUYANA'' THEN ''Guyana''
        WHEN ''HAÏTI'' THEN ''Haiti''
        WHEN ''ÎLES HEARD ET MCDONALD'' THEN ''Australia''
        WHEN ''SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)'' THEN ''Holy See (Vatican City State)''
        WHEN ''HONDURAS'' THEN ''Honduras''
        WHEN ''HONG KONG'' THEN ''China''
        WHEN ''HONGRIE'' THEN ''Hungary''
        WHEN ''ISLANDE'' THEN ''Iceland''
        WHEN ''INDE'' THEN ''India''
        WHEN ''INDONÉSIE'' THEN ''Indonesia''
        WHEN ''IRAN (RÉPUBLIQUE ISLAMIQUE D\\'') DE'' THEN ''Iran, Islamic Republic of''
        WHEN ''IRAK'' THEN ''Iraq''
        WHEN ''IRLANDE'' THEN ''Ireland''
        WHEN ''ÎLE DE MAN'' THEN ''United Kingdom''
        WHEN ''ISRAËL'' THEN ''Israel''
        WHEN ''ITALIE'' THEN ''Italy''
        WHEN ''JAMAÏQUE'' THEN ''Jamaica''
        WHEN ''JAPON'' THEN ''Japan''
        WHEN ''JERSEY'' THEN ''United Kingdom''
        WHEN ''JORDANIE'' THEN ''Jordan''
        WHEN ''KAZAKHSTAN'' THEN ''Kazakhstan''
        WHEN ''KENYA'' THEN ''Kenya''
        WHEN ''KIRIBATI'' THEN ''Kiribati''
        WHEN ''CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE'' THEN ''Korea, Democratic People\\''s Republic of''
        WHEN ''CORÉE, RÉPUBLIQUE DE'' THEN ''Korea, Republic of''
        WHEN ''KOWEIT'' THEN ''Kuwait''
        WHEN ''KIRGHIZISTAN'' THEN ''Kyrgyzstan''
        WHEN ''RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE LAO'' THEN ''Lao People\\''s Democratic Republic''
        WHEN ''LETTONIE'' THEN ''Latvia''
        WHEN ''LIBAN'' THEN ''Lebanon''
        WHEN ''LESOTHO'' THEN ''Lesotho''
        WHEN ''LIBÉRIA'' THEN ''Liberia''
        WHEN ''LIBYE'' THEN ''Libya''
        WHEN ''LIECHTENSTEIN'' THEN ''Liechtenstein''
        WHEN ''LITUANIE'' THEN ''Lithuania''
        WHEN ''LUXEMBOURG'' THEN ''Luxembourg''
        WHEN ''MACAO'' THEN ''China''
        WHEN ''MACÉDOINE, ANCIENNE RÉPUBLIQUE YOUGOSLAVE DE'' THEN ''Macedonia, the Former Yugoslav Republic of''
        WHEN ''MADAGASCAR'' THEN ''Madagascar''
        WHEN ''MALAWI'' THEN ''Malawi''
        WHEN ''MALAISIE'' THEN ''Malaysia''
        WHEN ''MALDIVES'' THEN ''Maldives''
        WHEN ''ILS AVAIENT'' THEN ''Mali''
        WHEN ''MALTE'' THEN ''Malta''
        WHEN ''ÎLES MARSHALL'' THEN ''Marshall Islands''
        WHEN ''MARTINIQUE'' THEN ''France''
        WHEN ''MAURITANIE'' THEN ''Mauritania''
        WHEN ''MAURICE'' THEN ''Mauritius''
        WHEN ''MAYOTTE'' THEN ''France''
        WHEN ''MEXIQUE'' THEN ''Mexico''
        WHEN ''MICRONÉSIE, ÉTATS FÉDÉRÉS DE'' THEN ''Micronesia, Federated States of''
        WHEN ''MOLDAVIE, RÉPUBLIQUE DE'' THEN ''Moldova, Republic of''
        WHEN ''MONACO'' THEN ''Monaco''
        WHEN ''MONGOLIE'' THEN ''Mongolia''
        WHEN ''MONTÉNÉGRO'' THEN ''Montenegro''
        WHEN ''MONTSERRAT'' THEN ''United Kingdom''
        WHEN ''MAROC'' THEN ''Morocco''
        WHEN ''MOZAMBIQUE'' THEN ''Mozambique''
        WHEN ''MYANMAR'' THEN ''Myanmar''
        WHEN ''NAMIBIE'' THEN ''Namibia''
        WHEN ''NAURU'' THEN ''Nauru''
        WHEN ''NÉPAL'' THEN ''Nepal''
        WHEN ''PAYS-BAS'' THEN ''Netherlands''
        WHEN ''NOUVELLE-CALÉDONIE'' THEN ''France''
        WHEN ''NOUVELLE-ZÉLANDE'' THEN ''New Zealand''
        WHEN ''NICARAGUA'' THEN ''Nicaragua''
        WHEN ''NIGER'' THEN ''Niger''
        WHEN ''NIGÉRIA'' THEN ''Nigeria''
        WHEN ''NIOUÉ'' THEN ''Niue''
        WHEN ''ÎLE NORFOLK'' THEN ''Australia''
        WHEN ''ÎLES MARIANNES DU NORD'' THEN ''United States''
        WHEN ''NORVÈGE'' THEN ''Norway''
        WHEN ''OMAN'' THEN ''Oman''
        WHEN ''PAKISTAN'' THEN ''Pakistan''
        WHEN ''PALAU'' THEN ''Palau''
        WHEN ''PALESTINE, ÉTAT DE'' THEN ''Palestine, State of''
        WHEN ''PANAMA'' THEN ''Panama''
        WHEN ''PAPOUASIE-NOUVELLE-GUINÉE'' THEN ''Papua New Guinea''
        WHEN ''PARAGUAY'' THEN ''Paraguay''
        WHEN ''PÉROU'' THEN ''Peru''
        WHEN ''PHILIPPINES'' THEN ''Philippines''
        WHEN ''PITCAIRN'' THEN ''United Kingdom''
        WHEN ''POLOGNE'' THEN ''Poland''
        WHEN ''PORTUGAL'' THEN ''Portugal''
        WHEN ''PORTO RICO'' THEN ''United States''
        WHEN ''QATAR'' THEN ''Qatar''
        WHEN ''RÉUNION'' THEN ''France''
        WHEN ''ROUMANIE'' THEN ''Romania''
        WHEN ''FÉDÉRATION DE RUSSIE'' THEN ''Russian Federation''
        WHEN ''RWANDA'' THEN ''Rwanda''
        WHEN ''SAINT-BARTHÉLEMY'' THEN ''France''
        WHEN ''SAINTE-HÉLÈNE, ASCENSION ET TRISTAN DA CUNHA'' THEN ''United Kingdom''
        WHEN ''SAINT-KITTS-ET-NEVIS'' THEN ''Saint Kitts and Nevis''
        WHEN ''SAINTE-LUCIE'' THEN ''Saint Lucia''
        WHEN ''SAINT-MARTIN (PARTIE FRANÇAISE)'' THEN ''France''
        WHEN ''SAINT-PIERRE-ET-MIQUELON'' THEN ''Saint Pierre and Miquelon''
        WHEN ''SAINT-VINCENT-ET-LES GRENADINES'' THEN ''Saint Vincent and the Grenadines''
        WHEN ''SAMOA'' THEN ''Samoa''
        WHEN ''SAINT-MARIN'' THEN ''San Marino''
        WHEN ''SAO TOMÉ-ET-PRINCIPE'' THEN ''Sao Tome and Principe''
        WHEN ''ARABIE SAOUDITE ARABIE'' THEN ''Saudi Arabia''
        WHEN ''SÉNÉGAL'' THEN ''Senegal''
        WHEN ''SERBIE'' THEN ''Serbia''
        WHEN ''SEYCHELLES'' THEN ''Seychelles''
        WHEN ''SIERRA LEONE'' THEN ''Sierra Leone''
        WHEN ''SINGAPOUR'' THEN ''Singapore''
        WHEN ''SINT MAARTEN (PARTIE NÉERLANDAISE)'' THEN ''Netherlands''
        WHEN ''SLOVAQUIE'' THEN ''Slovakia''
        WHEN ''SLOVÉNIE'' THEN ''Slovenia''
        WHEN ''ÎLES SALOMON'' THEN ''Solomon Islands''
        WHEN ''SOMALIE'' THEN ''Somalia''
        WHEN ''AFRIQUE DU SUD'' THEN ''South Africa''
        WHEN ''GÉORGIE DU SUD ET ÎLES SANDWICH DU SUD'' THEN ''United Kingdom''
        WHEN ''SOUDAN DU SUD'' THEN ''South Sudan''
        WHEN ''ESPAGNE'' THEN ''Spain''
        WHEN ''SRI LANKA'' THEN ''Sri Lanka''
        WHEN ''SOUDAN'' THEN ''Sudan''
        WHEN ''SURINAM'' THEN ''Suriname''
        WHEN ''SVALBARD ET JAN MAYEN'' THEN ''Norway''
        WHEN ''ESWATINI'' THEN ''Eswatini''
        WHEN ''SUÈDE'' THEN ''Sweden''
        WHEN ''SUISSE'' THEN ''Switzerland''
        WHEN ''RÉPUBLIQUE ARABE SYRIENNE'' THEN ''Syrian Arab Republic''
        WHEN ''TAÏWAN, PROVINCE DE CHINE'' THEN ''Taiwan, Province of China''
        WHEN ''TADJIKISTAN'' THEN ''Tajikistan''
        WHEN ''TANZANIE, RÉPUBLIQUE-UNIE DE'' THEN ''Tanzania, United Republic of''
        WHEN ''THAÏLANDE'' THEN ''Thailand''
        WHEN ''TIMOR-LESTE'' THEN ''Timor-Leste''
        WHEN ''ALLER'' THEN ''Togo''
        WHEN ''TOKÉLAOU'' THEN ''New Zealand''
        WHEN ''TONGA'' THEN ''Tonga''
        WHEN ''TRINITÉ-ET-TOBAGO'' THEN ''Trinidad and Tobago''
        WHEN ''TUNISIE'' THEN ''Tunisia''
        WHEN ''TURQUIE'' THEN ''Turkey''
        WHEN ''TURKMÉNISTAN'' THEN ''Turkmenistan''
        WHEN ''ÎLES TURQUES ET CAÏQUES'' THEN ''United Kingdom''
        WHEN ''TUVALU'' THEN ''Tuvalu''
        WHEN ''OUGANDA'' THEN ''Uganda''
        WHEN ''UKRAINE'' THEN ''Ukraine''
        WHEN ''ÉMIRATS ARABES UNIS'' THEN ''United Arab Emirates''
        WHEN ''ROYAUME-UNI'' THEN ''United Kingdom''
        WHEN ''ÉTATS-UNIS'' THEN ''United States''
        WHEN ''ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS'' THEN ''United States''
        WHEN ''URUGUAY''         THEN ''Uruguay''
        WHEN ''OUZBÉKISTAN''     THEN ''Uzbekistan''
        WHEN ''VANUATU''         THEN ''Vanuatu''
        WHEN ''VENEZUELA, RÉPUBLIQUE BOLIVARIENNE DU'' THEN ''Venezuela, Bolivarian Republic of''
        WHEN ''VIÊT NAM''        THEN ''Viet Nam''
        WHEN ''ÎLES VIERGES BRITANNIQUES'' THEN ''United Kingdom''
        WHEN ''ÎLES VIERGES ÉTATS-UNIS'' THEN ''United States''
        WHEN ''WALLIS-ET-FUTUNA'' THEN ''France''
        WHEN ''SAHARA OCCIDENTAL'' THEN ''Western Sahara''
        WHEN ''YÉMEN''           THEN ''Yemen''
        WHEN ''ZAMBIE''          THEN ''Zambia''
        WHEN ''ZIMBABWE''        THEN ''Zimbabwe''
        --2 digit codes----------------------------------------------------------------------------------------------------------------
        WHEN ''AF'' THEN ''Afghanistan''
        WHEN ''AX'' THEN ''Finland''
        WHEN ''AL'' THEN ''Albania''
        WHEN ''DZ'' THEN ''Algeria''
        WHEN ''AS'' THEN ''United States''
        WHEN ''AD'' THEN ''Andorra''
        WHEN ''AO'' THEN ''Angola''
        WHEN ''AI'' THEN ''United Kingdom''
        WHEN ''AQ'' THEN ''Antarctica''
        WHEN ''AG'' THEN ''Antigua and Barbuda''
        WHEN ''AR'' THEN ''Argentina''
        WHEN ''AM'' THEN ''Armenia''
        WHEN ''AW'' THEN ''Netherlands''
        WHEN ''AU'' THEN ''Australia''
        WHEN ''AT'' THEN ''Austria''
        WHEN ''AZ'' THEN ''Azerbaijan''
        WHEN ''BS'' THEN ''Bahamas''
        WHEN ''BH'' THEN ''Bahrain''
        WHEN ''BD'' THEN ''Bangladesh''
        WHEN ''BB'' THEN ''Barbados''
        WHEN ''BY'' THEN ''Belarus''
        WHEN ''BE'' THEN ''Belgium''
        WHEN ''BZ'' THEN ''Belize''
        WHEN ''BJ'' THEN ''Benin''
        WHEN ''BM'' THEN ''United Kingdom''
        WHEN ''BT'' THEN ''Bhutan''
        WHEN ''BO'' THEN ''Bolivia, Plurinational State of''
        WHEN ''BQ'' THEN ''Netherlands''
        WHEN ''BA'' THEN ''Bosnia and Herzegovina''
        WHEN ''BW'' THEN ''Botswana''
        WHEN ''BV'' THEN ''Norway''
        WHEN ''BR'' THEN ''Brazil''
        WHEN ''IO'' THEN ''United Kingdom''
        WHEN ''BN'' THEN ''Brunei Darussalam''
        WHEN ''BG'' THEN ''Bulgaria''
        WHEN ''BF'' THEN ''Burkina Faso''
        WHEN ''BI'' THEN ''Burundi''
        WHEN ''KH'' THEN ''Cambodia''
        WHEN ''CM'' THEN ''Cameroon''
        WHEN ''CA'' THEN ''Canada''
        WHEN ''CV'' THEN ''Cape Verde''
        WHEN ''KY'' THEN ''United Kingdom''
        WHEN ''CF'' THEN ''Central African Republic''
        WHEN ''TD'' THEN ''Chad''
        WHEN ''CL'' THEN ''Chile''
        WHEN ''CN'' THEN ''China''
        WHEN ''CX'' THEN ''Australia''
        WHEN ''CC'' THEN ''Australia''
        WHEN ''CO'' THEN ''Colombia''
        WHEN ''KM'' THEN ''Comoros''
        WHEN ''CG'' THEN ''Congo''
        WHEN ''CD'' THEN ''Congo, the Democratic Republic of the''
        WHEN ''CK'' THEN ''New Zealand''
        WHEN ''CR'' THEN ''Costa Rica''
        WHEN ''CI'' THEN ''Côte d\\''Ivoire''
        WHEN ''HR'' THEN ''Croatia''
        WHEN ''CU'' THEN ''Cuba''
        WHEN ''CW'' THEN ''Netherlands''
        WHEN ''CY'' THEN ''Cyprus''
        WHEN ''CZ'' THEN ''Czech Republic''
        WHEN ''DK'' THEN ''Denmark''
        WHEN ''DJ'' THEN ''Djibouti''
        WHEN ''DM'' THEN ''Dominica''
        WHEN ''DO'' THEN ''Dominican Republic''
        WHEN ''EC'' THEN ''Ecuador''
        WHEN ''EG'' THEN ''Egypt''
        WHEN ''SV'' THEN ''El Salvador''
        WHEN ''GQ'' THEN ''Equatorial Guinea''
        WHEN ''ER'' THEN ''Eritrea''
        WHEN ''EE'' THEN ''Estonia''
        WHEN ''ET'' THEN ''Ethiopia''
        WHEN ''FK'' THEN ''United Kingdom''
        WHEN ''FO'' THEN ''Denmark''
        WHEN ''FJ'' THEN ''Fiji''
        WHEN ''FI'' THEN ''Finland''
        WHEN ''FR'' THEN ''France''
        WHEN ''GF'' THEN ''France''
        WHEN ''PF'' THEN ''France''
        WHEN ''TF'' THEN ''France''
        WHEN ''GA'' THEN ''Gabon''
        WHEN ''GM'' THEN ''Gambia''
        WHEN ''GE'' THEN ''Georgia''
        WHEN ''DE'' THEN ''Germany''
        WHEN ''GH'' THEN ''Ghana''
        WHEN ''GI'' THEN ''United Kingdom''
        WHEN ''GR'' THEN ''Greece''
        WHEN ''GL'' THEN ''Denmark''
        WHEN ''GD'' THEN ''Grenada''
        WHEN ''GP'' THEN ''France''
        WHEN ''GU'' THEN ''United States''
        WHEN ''GT'' THEN ''Guatemala''
        WHEN ''GG'' THEN ''United Kingdom''
        WHEN ''GN'' THEN ''Guinea''
        WHEN ''GW'' THEN ''Guinea-Bissau''
        WHEN ''GY'' THEN ''Guyana''
        WHEN ''HT'' THEN ''Haiti''
        WHEN ''HM'' THEN ''Australia''
        WHEN ''VA'' THEN ''Holy See (Vatican City State)''
        WHEN ''HN'' THEN ''Honduras''
        WHEN ''HK'' THEN ''China''
        WHEN ''HU'' THEN ''Hungary''
        WHEN ''IS'' THEN ''Iceland''
        WHEN ''IN'' THEN ''India''
        WHEN ''ID'' THEN ''Indonesia''
        WHEN ''IR'' THEN ''Iran, Islamic Republic of''
        WHEN ''IQ'' THEN ''Iraq''
        WHEN ''IE'' THEN ''Ireland''
        WHEN ''IM'' THEN ''United Kingdom''
        WHEN ''IL'' THEN ''Israel''
        WHEN ''IT'' THEN ''Italy''
        WHEN ''JM'' THEN ''Jamaica''
        WHEN ''JP'' THEN ''Japan''
        WHEN ''JE'' THEN ''United Kingdom''
        WHEN ''JO'' THEN ''Jordan''
        WHEN ''KZ'' THEN ''Kazakhstan''
        WHEN ''KE'' THEN ''Kenya''
        WHEN ''KI'' THEN ''Kiribati''
        WHEN ''KP'' THEN ''Korea, Democratic People\\''s Republic of''
        WHEN ''KR'' THEN ''Korea, Republic of''
        WHEN ''KW'' THEN ''Kuwait''
        WHEN ''KG'' THEN ''Kyrgyzstan''
        WHEN ''LA'' THEN ''Lao People\\''s Democratic Republic''
        WHEN ''LV'' THEN ''Latvia''
        WHEN ''LB'' THEN ''Lebanon''
        WHEN ''LS'' THEN ''Lesotho''
        WHEN ''LR'' THEN ''Liberia''
        WHEN ''LY'' THEN ''Libya''
        WHEN ''LI'' THEN ''Liechtenstein''
        WHEN ''LT'' THEN ''Lithuania''
        WHEN ''LU'' THEN ''Luxembourg''
        WHEN ''MO'' THEN ''China''
        WHEN ''MK'' THEN ''Macedonia, the Former Yugoslav Republic of''
        WHEN ''MG'' THEN ''Madagascar''
        WHEN ''MW'' THEN ''Malawi''
        WHEN ''MY'' THEN ''Malaysia''
        WHEN ''MV'' THEN ''Maldives''
        WHEN ''ML'' THEN ''Mali''
        WHEN ''MT'' THEN ''Malta''
        WHEN ''MH'' THEN ''Marshall Islands''
        WHEN ''MQ'' THEN ''France''
        WHEN ''MR'' THEN ''Mauritania''
        WHEN ''MU'' THEN ''Mauritius''
        WHEN ''YT'' THEN ''France''
        WHEN ''MX'' THEN ''Mexico''
        WHEN ''FM'' THEN ''Micronesia, Federated States of''
        WHEN ''MD'' THEN ''Moldova, Republic of''
        WHEN ''MC'' THEN ''Monaco''
        WHEN ''MN'' THEN ''Mongolia''
        WHEN ''ME'' THEN ''Montenegro''
        WHEN ''MS'' THEN ''United Kingdom''
        WHEN ''MA'' THEN ''Morocco''
        WHEN ''MZ'' THEN ''Mozambique''
        WHEN ''MM'' THEN ''Myanmar''
        WHEN ''NA'' THEN ''Namibia''
        WHEN ''NR'' THEN ''Nauru''
        WHEN ''NP'' THEN ''Nepal''
        WHEN ''NL'' THEN ''Netherlands''
        WHEN ''NC'' THEN ''France''
        WHEN ''NZ'' THEN ''New Zealand''
        WHEN ''NI'' THEN ''Nicaragua''
        WHEN ''NE'' THEN ''Niger''
        WHEN ''NG'' THEN ''Nigeria''
        WHEN ''NU'' THEN ''Niue''
        WHEN ''NF'' THEN ''Australia''
        WHEN ''MP'' THEN ''United States''
        WHEN ''NO'' THEN ''Norway''
        WHEN ''OM'' THEN ''Oman''
        WHEN ''PK'' THEN ''Pakistan''
        WHEN ''PW'' THEN ''Palau''
        WHEN ''PS'' THEN ''Palestine, State of''
        WHEN ''PA'' THEN ''Panama''
        WHEN ''PG'' THEN ''Papua New Guinea''
        WHEN ''PY'' THEN ''Paraguay''
        WHEN ''PE'' THEN ''Peru''
        WHEN ''PH'' THEN ''Philippines''
        WHEN ''PN'' THEN ''United Kingdom''
        WHEN ''PL'' THEN ''Poland''
        WHEN ''PT'' THEN ''Portugal''
        WHEN ''PR'' THEN ''United States''
        WHEN ''QA'' THEN ''Qatar''
        WHEN ''RE'' THEN ''France''
        WHEN ''RO'' THEN ''Romania''
        WHEN ''RU'' THEN ''Russian Federation''
        WHEN ''RW'' THEN ''Rwanda''
        WHEN ''BL'' THEN ''France''
        WHEN ''SH'' THEN ''United Kingdom''
        WHEN ''KN'' THEN ''Saint Kitts and Nevis''
        WHEN ''LC'' THEN ''Saint Lucia''
        WHEN ''MF'' THEN ''France''
        WHEN ''PM'' THEN ''Saint Pierre and Miquelon''
        WHEN ''VC'' THEN ''Saint Vincent and the Grenadines''
        WHEN ''WS'' THEN ''Samoa''
        WHEN ''SM'' THEN ''San Marino''
        WHEN ''ST'' THEN ''Sao Tome and Principe''
        WHEN ''SA'' THEN ''Saudi Arabia''
        WHEN ''SN'' THEN ''Senegal''
        WHEN ''RS'' THEN ''Serbia''
        WHEN ''SC'' THEN ''Seychelles''
        WHEN ''SL'' THEN ''Sierra Leone''
        WHEN ''SG'' THEN ''Singapore''
        WHEN ''SX'' THEN ''Netherlands''
        WHEN ''SK'' THEN ''Slovakia''
        WHEN ''SI'' THEN ''Slovenia''
        WHEN ''SB'' THEN ''Solomon Islands''
        WHEN ''SO'' THEN ''Somalia''
        WHEN ''ZA'' THEN ''South Africa''
        WHEN ''GS'' THEN ''United Kingdom''
        WHEN ''SS'' THEN ''South Sudan''
        WHEN ''ES'' THEN ''Spain''
        WHEN ''LK'' THEN ''Sri Lanka''
        WHEN ''SD'' THEN ''Sudan''
        WHEN ''SR'' THEN ''Suriname''
        WHEN ''SJ'' THEN ''Norway''
        WHEN ''SZ'' THEN ''Eswatini''
        WHEN ''SE'' THEN ''Sweden''
        WHEN ''CH'' THEN ''Switzerland''
        WHEN ''SY'' THEN ''Syrian Arab Republic''
        WHEN ''TW'' THEN ''Taiwan, Province of China''
        WHEN ''TJ'' THEN ''Tajikistan''
        WHEN ''TZ'' THEN ''Tanzania, United Republic of''
        WHEN ''TH'' THEN ''Thailand''
        WHEN ''TL'' THEN ''Timor-Leste''
        WHEN ''TG'' THEN ''Togo''
        WHEN ''TK'' THEN ''New Zealand''
        WHEN ''TO'' THEN ''Tonga''
        WHEN ''TT'' THEN ''Trinidad and Tobago''
        WHEN ''TN'' THEN ''Tunisia''
        WHEN ''TR'' THEN ''Turkey''
        WHEN ''TM'' THEN ''Turkmenistan''
        WHEN ''TC'' THEN ''United Kingdom''
        WHEN ''TV'' THEN ''Tuvalu''
        WHEN ''UG'' THEN ''Uganda''
        WHEN ''UA'' THEN ''Ukraine''
        WHEN ''AE'' THEN ''United Arab Emirates''
        WHEN ''GB'' THEN ''United Kingdom''
        WHEN ''US'' THEN ''United States''
        WHEN ''UM'' THEN ''United States''
        WHEN ''UY'' THEN ''Uruguay''
        WHEN ''UZ'' THEN ''Uzbekistan''
        WHEN ''VU'' THEN ''Vanuatu''
        WHEN ''VE'' THEN ''Venezuela, Bolivarian Republic of''
        WHEN ''VN'' THEN ''Viet Nam''
        WHEN ''VG'' THEN ''United Kingdom''
        WHEN ''VI'' THEN ''United States''
        WHEN ''WF'' THEN ''France''
        WHEN ''EH'' THEN ''Western Sahara''
        WHEN ''YE'' THEN ''Yemen''
        WHEN ''ZM'' THEN ''Zambia''
        WHEN ''ZW'' THEN ''Zimbabwe''
        --3 digit codes----------------------------------------------------------------------------------------------------------------
        WHEN ''AFG'' THEN ''Afghanistan''
        WHEN ''ALA'' THEN ''Finland''
        WHEN ''ALB'' THEN ''Albania''
        WHEN ''DZA'' THEN ''Algeria''
        WHEN ''ASM'' THEN ''United States''
        WHEN ''AND'' THEN ''Andorra''
        WHEN ''AGO'' THEN ''Angola''
        WHEN ''AIA'' THEN ''United Kingdom''
        WHEN ''ATA'' THEN ''Antarctica''
        WHEN ''ATG'' THEN ''Antigua and Barbuda''
        WHEN ''ARG'' THEN ''Argentina''
        WHEN ''ARM'' THEN ''Armenia''
        WHEN ''ABW'' THEN ''Netherlands''
        WHEN ''AUS'' THEN ''Australia''
        WHEN ''AUT'' THEN ''Austria''
        WHEN ''AZE'' THEN ''Azerbaijan''
        WHEN ''BHS'' THEN ''Bahamas''
        WHEN ''BHR'' THEN ''Bahrain''
        WHEN ''BGD'' THEN ''Bangladesh''
        WHEN ''BRB'' THEN ''Barbados''
        WHEN ''BLR'' THEN ''Belarus''
        WHEN ''BEL'' THEN ''Belgium''
        WHEN ''BLZ'' THEN ''Belize''
        WHEN ''BEN'' THEN ''Benin''
        WHEN ''BMU'' THEN ''United Kingdom''
        WHEN ''BTN'' THEN ''Bhutan''
        WHEN ''BOL'' THEN ''Bolivia, Plurinational State of''
        WHEN ''BES'' THEN ''Netherlands''
        WHEN ''BIH'' THEN ''Bosnia and Herzegovina''
        WHEN ''BWA'' THEN ''Botswana''
        WHEN ''BVT'' THEN ''Norway''
        WHEN ''BRA'' THEN ''Brazil''
        WHEN ''IOT'' THEN ''United Kingdom''
        WHEN ''BRN'' THEN ''Brunei Darussalam''
        WHEN ''BGR'' THEN ''Bulgaria''
        WHEN ''BFA'' THEN ''Burkina Faso''
        WHEN ''BDI'' THEN ''Burundi''
        WHEN ''KHM'' THEN ''Cambodia''
        WHEN ''CMR'' THEN ''Cameroon''
        WHEN ''CAN'' THEN ''Canada''
        WHEN ''CPV'' THEN ''Cape Verde''
        WHEN ''CYM'' THEN ''United Kingdom''
        WHEN ''CAF'' THEN ''Central African Republic''
        WHEN ''TCD'' THEN ''Chad''
        WHEN ''CHL'' THEN ''Chile''
        WHEN ''CHN'' THEN ''China''
        WHEN ''CXR'' THEN ''Australia''
        WHEN ''CCK'' THEN ''Australia''
        WHEN ''COL'' THEN ''Colombia''
        WHEN ''COM'' THEN ''Comoros''
        WHEN ''COG'' THEN ''Congo''
        WHEN ''COD'' THEN ''Congo, the Democratic Republic of the''
        WHEN ''COK'' THEN ''New Zealand''
        WHEN ''CRI'' THEN ''Costa Rica''
        WHEN ''CIV'' THEN ''Côte d\\''Ivoire''
        WHEN ''HRV'' THEN ''Croatia''
        WHEN ''CUB'' THEN ''Cuba''
        WHEN ''CUW'' THEN ''Netherlands''
        WHEN ''CYP'' THEN ''Cyprus''
        WHEN ''CZE'' THEN ''Czech Republic''
        WHEN ''DNK'' THEN ''Denmark''
        WHEN ''DJI'' THEN ''Djibouti''
        WHEN ''DMA'' THEN ''Dominica''
        WHEN ''DOM'' THEN ''Dominican Republic''
        WHEN ''ECU'' THEN ''Ecuador''
        WHEN ''EGY'' THEN ''Egypt''
        WHEN ''SLV'' THEN ''El Salvador''
        WHEN ''GNQ'' THEN ''Equatorial Guinea''
        WHEN ''ERI'' THEN ''Eritrea''
        WHEN ''EST'' THEN ''Estonia''
        WHEN ''ETH'' THEN ''Ethiopia''
        WHEN ''FLK'' THEN ''United Kingdom''
        WHEN ''FRO'' THEN ''Denmark''
        WHEN ''FJI'' THEN ''Fiji''
        WHEN ''FIN'' THEN ''Finland''
        WHEN ''FRA'' THEN ''France''
        WHEN ''GUF'' THEN ''France''
        WHEN ''PYF'' THEN ''France''
        WHEN ''ATF'' THEN ''France''
        WHEN ''GAB'' THEN ''Gabon''
        WHEN ''GMB'' THEN ''Gambia''
        WHEN ''GEO'' THEN ''Georgia''
        WHEN ''DEU'' THEN ''Germany''
        WHEN ''GHA'' THEN ''Ghana''
        WHEN ''GIB'' THEN ''United Kingdom''
        WHEN ''GRC'' THEN ''Greece''
        WHEN ''GRL'' THEN ''Denmark''
        WHEN ''GRD'' THEN ''Grenada''
        WHEN ''GLP'' THEN ''France''
        WHEN ''GUM'' THEN ''United States''
        WHEN ''GTM'' THEN ''Guatemala''
        WHEN ''GGY'' THEN ''United Kingdom''
        WHEN ''GIN'' THEN ''Guinea''
        WHEN ''GNB'' THEN ''Guinea-Bissau''
        WHEN ''GUY'' THEN ''Guyana''
        WHEN ''HTI'' THEN ''Haiti''
        WHEN ''HMD'' THEN ''Australia''
        WHEN ''VAT'' THEN ''Holy See (Vatican City State)''
        WHEN ''HND'' THEN ''Honduras''
        WHEN ''HKG'' THEN ''China''
        WHEN ''HUN'' THEN ''Hungary''
        WHEN ''ISL'' THEN ''Iceland''
        WHEN ''IND'' THEN ''India''
        WHEN ''IDN'' THEN ''Indonesia''
        WHEN ''IRN'' THEN ''Iran, Islamic Republic of''
        WHEN ''IRQ'' THEN ''Iraq''
        WHEN ''IRL'' THEN ''Ireland''
        WHEN ''IMN'' THEN ''United Kingdom''
        WHEN ''ISR'' THEN ''Israel''
        WHEN ''ITA'' THEN ''Italy''
        WHEN ''JAM'' THEN ''Jamaica''
        WHEN ''JPN'' THEN ''Japan''
        WHEN ''JEY'' THEN ''United Kingdom''
        WHEN ''JOR'' THEN ''Jordan''
        WHEN ''KAZ'' THEN ''Kazakhstan''
        WHEN ''KEN'' THEN ''Kenya''
        WHEN ''KIR'' THEN ''Kiribati''
        WHEN ''PRK'' THEN ''Korea, Democratic People\\''s Republic of''
        WHEN ''KOR'' THEN ''Korea, Republic of''
        WHEN ''KWT'' THEN ''Kuwait''
        WHEN ''KGZ'' THEN ''Kyrgyzstan''
        WHEN ''LAO'' THEN ''Lao People\\''s Democratic Republic''
        WHEN ''LVA'' THEN ''Latvia''
        WHEN ''LBN'' THEN ''Lebanon''
        WHEN ''LSO'' THEN ''Lesotho''
        WHEN ''LBR'' THEN ''Liberia''
        WHEN ''LBY'' THEN ''Libya''
        WHEN ''LIE'' THEN ''Liechtenstein''
        WHEN ''LTU'' THEN ''Lithuania''
        WHEN ''LUX'' THEN ''Luxembourg''
        WHEN ''MAC'' THEN ''China''
        WHEN ''MKD'' THEN ''Macedonia, the Former Yugoslav Republic of''
        WHEN ''MDG'' THEN ''Madagascar''
        WHEN ''MWI'' THEN ''Malawi''
        WHEN ''MYS'' THEN ''Malaysia''
        WHEN ''MDV'' THEN ''Maldives''
        WHEN ''MLI'' THEN ''Mali''
        WHEN ''MLT'' THEN ''Malta''
        WHEN ''MHL'' THEN ''Marshall Islands''
        WHEN ''MTQ'' THEN ''France''
        WHEN ''MRT'' THEN ''Mauritania''
        WHEN ''MUS'' THEN ''Mauritius''
        WHEN ''MYT'' THEN ''France''
        WHEN ''MEX'' THEN ''Mexico''
        WHEN ''FSM'' THEN ''Micronesia, Federated States of''
        WHEN ''MDA'' THEN ''Moldova, Republic of''
        WHEN ''MCO'' THEN ''Monaco''
        WHEN ''MNG'' THEN ''Mongolia''
        WHEN ''MNE'' THEN ''Montenegro''
        WHEN ''MSR'' THEN ''United Kingdom''
        WHEN ''MAR'' THEN ''Morocco''
        WHEN ''MOZ'' THEN ''Mozambique''
        WHEN ''MMR'' THEN ''Myanmar''
        WHEN ''NAM'' THEN ''Namibia''
        WHEN ''NRU'' THEN ''Nauru''
        WHEN ''NPL'' THEN ''Nepal''
        WHEN ''NLD'' THEN ''Netherlands''
        WHEN ''NCL'' THEN ''France''
        WHEN ''NZL'' THEN ''New Zealand''
        WHEN ''NIC'' THEN ''Nicaragua''
        WHEN ''NER'' THEN ''Niger''
        WHEN ''NGA'' THEN ''Nigeria''
        WHEN ''NIU'' THEN ''Niue''
        WHEN ''NFK'' THEN ''Australia''
        WHEN ''MNP'' THEN ''United States''
        WHEN ''NOR'' THEN ''Norway''
        WHEN ''OMN'' THEN ''Oman''
        WHEN ''PAK'' THEN ''Pakistan''
        WHEN ''PLW'' THEN ''Palau''
        WHEN ''PSE'' THEN ''Palestine, State of''
        WHEN ''PAN'' THEN ''Panama''
        WHEN ''PNG'' THEN ''Papua New Guinea''
        WHEN ''PRY'' THEN ''Paraguay''
        WHEN ''PER'' THEN ''Peru''
        WHEN ''PHL'' THEN ''Philippines''
        WHEN ''PCN'' THEN ''United Kingdom''
        WHEN ''POL'' THEN ''Poland''
        WHEN ''PRT'' THEN ''Portugal''
        WHEN ''PRI'' THEN ''United States''
        WHEN ''QAT'' THEN ''Qatar''
        WHEN ''REU'' THEN ''France''
        WHEN ''ROU'' THEN ''Romania''
        WHEN ''RUS'' THEN ''Russian Federation''
        WHEN ''RWA'' THEN ''Rwanda''
        WHEN ''BLM'' THEN ''France''
        WHEN ''SHN'' THEN ''United Kingdom''
        WHEN ''KNA'' THEN ''Saint Kitts and Nevis''
        WHEN ''LCA'' THEN ''Saint Lucia''
        WHEN ''MAF'' THEN ''France''
        WHEN ''SPM'' THEN ''Saint Pierre and Miquelon''
        WHEN ''VCT'' THEN ''Saint Vincent and the Grenadines''
        WHEN ''WSM'' THEN ''Samoa''
        WHEN ''SMR'' THEN ''San Marino''
        WHEN ''STP'' THEN ''Sao Tome and Principe''
        WHEN ''SAU'' THEN ''Saudi Arabia''
        WHEN ''SEN'' THEN ''Senegal''
        WHEN ''SRB'' THEN ''Serbia''
        WHEN ''SYC'' THEN ''Seychelles''
        WHEN ''SLE'' THEN ''Sierra Leone''
        WHEN ''SGP'' THEN ''Singapore''
        WHEN ''SXM'' THEN ''Netherlands''
        WHEN ''SVK'' THEN ''Slovakia''
        WHEN ''SVN'' THEN ''Slovenia''
        WHEN ''SLB'' THEN ''Solomon Islands''
        WHEN ''SOM'' THEN ''Somalia''
        WHEN ''ZAF'' THEN ''South Africa''
        WHEN ''SGS'' THEN ''United Kingdom''
        WHEN ''SSD'' THEN ''South Sudan''
        WHEN ''ESP'' THEN ''Spain''
        WHEN ''LKA'' THEN ''Sri Lanka''
        WHEN ''SDN'' THEN ''Sudan''
        WHEN ''SUR'' THEN ''Suriname''
        WHEN ''SJM'' THEN ''Norway''
        WHEN ''SWZ'' THEN ''Eswatini''
        WHEN ''SWE'' THEN ''Sweden''
        WHEN ''CHE'' THEN ''Switzerland''
        WHEN ''SYR'' THEN ''Syrian Arab Republic''
        WHEN ''TWN'' THEN ''Taiwan, Province of China''
        WHEN ''TJK'' THEN ''Tajikistan''
        WHEN ''TZA'' THEN ''Tanzania, United Republic of''
        WHEN ''THA'' THEN ''Thailand''
        WHEN ''TLS'' THEN ''Timor-Leste''
        WHEN ''TGO'' THEN ''Togo''
        WHEN ''TKL'' THEN ''New Zealand''
        WHEN ''TON'' THEN ''Tonga''
        WHEN ''TTO'' THEN ''Trinidad and Tobago''
        WHEN ''TUN'' THEN ''Tunisia''
        WHEN ''TUR'' THEN ''Turkey''
        WHEN ''TKM'' THEN ''Turkmenistan''
        WHEN ''TCA'' THEN ''United Kingdom''
        WHEN ''TUV'' THEN ''Tuvalu''
        WHEN ''UGA'' THEN ''Uganda''
        WHEN ''UKR'' THEN ''Ukraine''
        WHEN ''ARE'' THEN ''United Arab Emirates''
        WHEN ''GBR'' THEN ''United Kingdom''
        WHEN ''USA'' THEN ''United States''
        WHEN ''UMI'' THEN ''United States''
        WHEN ''URY'' THEN ''Uruguay''
        WHEN ''UZB'' THEN ''Uzbekistan''
        WHEN ''VUT'' THEN ''Vanuatu''
        WHEN ''VEN'' THEN ''Venezuela, Bolivarian Republic of''
        WHEN ''VNM'' THEN ''Viet Nam''
        WHEN ''VGB'' THEN ''United Kingdom''
        WHEN ''VIR'' THEN ''United States''
        WHEN ''WLF'' THEN ''France''
        WHEN ''ESH'' THEN ''Western Sahara''
        WHEN ''YEM'' THEN ''Yemen''
        WHEN ''ZMB'' THEN ''Zambia''
        WHEN ''ZWE'' THEN ''Zimbabwe''     
        ----------------------------------------------------------------------------------------------------------------
        ELSE INITCAP(COUNTRY_CODE) 
    END AS COO
';