USE ROLE sysadmin;
{% if environment == 'PROD' %}
    {% set sufix = '' %}
{% elif environment == 'TEST' %}
    {% set sufix = '_'+ environment %}
{% elif environment == 'DEV' %}
    {% set sufix = '_'+ environment %}
{% endif %} 

CREATE OR ALTER TABLE SOR_AND_STOCK{{ sufix }}.PROCESS.DISTRIBUTOR_SETTINGS (
	ID NUMBER(38,0) autoincrement start 1 increment 1 order,
	DISTRIBUTOR_NAME VARCHAR(16777216),
	TYPE VARCHAR(16777216),
	NAME_PATTERNS VARCHAR(16777216),
	PARSING_PATTERN VARCHAR(16777216),
	LIST_SKIP_ROWS VARCHAR(16777216),
	LIST_HEADER VARCHAR(16777216),
	LIST_NAMES VARCHAR(16777216),
	UPDATE_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATE_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	OTHER_SETTINGS VARIANT,
	CSV_DELIMITER VARCHAR(16777216)
);